### ISSUE TITLE
[Not an issue] Just wanted to say, great package!

### ISSUE THREAD

**Issue by Akira13641** [aferust/dvector#1]
Relatively new to D here, but after doing some comparisons of both various Dub packages and things in the D standard library such as `std.container.Array`, I found `Dvector` to be more performant than anything else by quite a large margin.  
  
For example, switching a `std.container.Array` used by a memory pool class I wrote for an [implementation of the popular "Binary Trees" benchmark I was doing](https://github.com/Akira13641/BinaryTreesBenchmark) over to a `Dvector` improved the average runtimes by around a full five seconds!

**Comment by aferust** [comment]
Thank you for appreciation. Some time ago, I needed a dynamic array compatible with betterC, but could not find one. Maybe there are others, but I just didn't find one. It is very simple, and is working good so far for me. But be careful that I am still finding bugs. Last night, I realized that I forgot to multiply memory amount for memmove with T.sizeof and immediately made a commit and updated dub repo :) It is also working good for some phobos functions like sort and retro. However, one must be also careful for func save() because its allocates a new array. I am not sure when and where phobos uses save() implicitly.  User has to be sure that he or she can always keep a handle of the copied vectors to free them safely.

**Comment by Akira13641** [comment]
I'm only using `pushBack` and `free` at the moment. I'll keep what you said in mind though! Will close this issue now I guess.
